(function($){
function shell(){
 const path=location.pathname.split('/').pop()||'index.html';
 const active=path==='index.html'?'Home':path==='about.html'?'About Us':path==='contact.html'?'Contact Us':'Products';
 const menu=categories.map(c=>`<a href="products.html?cat=${encodeURIComponent(c[1])}"><i class="bi ${c[2]}"></i>${c[0]}</a>`).join('');
 $('#siteHeader').html(`<div class="topbar"><div class="container topin"><div><i class="bi bi-telephone"></i><span>+971 50 254 2258</span><i class="bi bi-telephone"></i><span>+971 4 347 4484</span></div><div><i class="bi bi-envelope"></i> connect@mktgt.com</div></div></div><nav class="nav"><div class="container navin"><a class="logo logo-image" href="index.html" aria-label="Modern Services and Trading"><img src="assets/logo/modern-services-trading.png" alt="Modern Services and Trading"></a><button class="hamb" aria-label="Menu"><i class="bi bi-list"></i></button><div class="navlinks"> <a class="${active==='Home'?'active':''}" href="index.html">Home</a><a class="${active==='About Us'?'active':''}" href="about.html">About Us</a><div class="navdrop"><a class="${active==='Products'?'active':''}" href="products.html">Products <i class="bi bi-chevron-down"></i></a><div class="dropdown">${menu}</div></div><a href="brands.html">Brands</a><a class="${active==='Contact Us'?'active':''}" href="contact.html">Contact Us</a></div><div class="navsearch"><i class="bi bi-search"></i><input id="globalSearch" placeholder="Search Product"></div></div></nav>`);
 $('#siteFooter').html(`<footer class="footer"><div class="container footgrid"><div><a class="logo logo-image" href="index.html" aria-label="Modern Services and Trading"><img src="assets/logo/modern-services-trading.png" alt="Modern Services and Trading"></a><p>Premium food products, trusted sourcing and reliable distribution across the UAE and GCC.</p></div><div><h4>QUICK LINKS</h4><a href="about.html">About Us</a><a href="products.html">Products</a><a href="brands.html">Our Brands</a><a href="contact.html">Contact Us</a></div><div><h4>GET IN TOUCH</h4><p>+971 4 347 44 84</p><p>+971 50 254 2258</p><p>connect@mktgt.com</p><p>Po Box 234174, Ras Al Khor Industrial Area 2, Dubai</p></div></div><div class="copyright">© 2026 Modern Services and Trading L.L.C. All rights reserved.</div></footer>`);
}
function home(){
 if(!$('#heroSlider').length)return;
 const slides=[['BRINGING WORLD-CLASS PREMIUM QUALITY FOOD PRODUCTS TO STAR KITCHENS','Quality products. Reliable supply.','Explore Products'],['YOUR ONE-STOP FOOD SUPPLY PARTNER','From global sourcing to temperature-controlled distribution.','Discover Our Range'],['PREMIUM PRODUCTS FOR PROFESSIONAL KITCHENS','Serving hotels, restaurants, catering, bakeries and wholesalers.','Contact Us']];
 $('#heroSlider').html(slides.map((s,i)=>`<div class="hero-slide ${i===0?'active':''}"><div class="container hero-content"><p class="kicker">Modern Services and Trading</p><h1>${s[0]}</h1><p>${s[1]}</p><a class="btn" href="${i===2?'contact.html':'products.html'}">${s[2]} <i class="bi bi-arrow-right"></i></a></div></div>`).join(''));
 $('#heroDots').html(slides.map((_,i)=>`<button class="${i===0?'active':''}" data-slide="${i}"></button>`).join(''));
 let current=0; function go(n){current=n;$('.hero-slide').removeClass('active').eq(n).addClass('active');$('.hero-dots button').removeClass('active').eq(n).addClass('active')} $('.hero-dots').on('click','button',function(){go(+$(this).data('slide'))}); setInterval(()=>go((current+1)%slides.length),6000);
 $('#homeCategories').html(categories.slice(0,8).map(c=>`<a class="category-card" href="products.html?cat=${c[1]}"><div class="category-icon"><i class="bi ${c[2]}"></i></div><h3>${c[0]}</h3><span>Explore range</span></a>`).join(''));
}
function productPage(){if(!$('#productGrid').length)return; let per=12,page=1,params=new URLSearchParams(location.search),cat=params.get('cat')||'',q=params.get('q')||'';$('#productSearch').val(q);$('#filterList').html(`<button data-cat="" class="${!cat?'active':''}">All Categories</button>`+categories.map(c=>`<button data-cat="${c[1]}" class="${cat===c[1]?'active':''}">${c[0]}</button>`).join(''));
 function render(){let list=products.filter(p=>(!cat||p.slug===cat)&&(!q||p.name.toLowerCase().includes(q.toLowerCase()))),pages=Math.max(1,Math.ceil(list.length/per));page=Math.min(page,pages);let start=(page-1)*per;$('#resultCount').text(`${list.length} products`);$('#productGrid').html(list.slice(start,start+per).map(p=>{let ic=categories.find(c=>c[1]===p.slug)?.[2]||'bi-box';let art=p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:`<i class="bi ${ic}"></i>`;return `<article class="product-card"><a class="product-art" href="product-detail.html?id=${p.id}">${art}</a><div class="product-body"><small>${p.category}</small><h3>${p.name}</h3><a href="product-detail.html?id=${p.id}">READ MORE <i class="bi bi-arrow-right"></i></a></div></article>`}).join('')||'<div class="empty">No products found.</div>');$('#pagination').html(Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${i+1===page?'active':''}">${i+1}</button>`).join(''))}
 $('#productSearch').on('input',function(){q=this.value;page=1;render()});$('#filterList').on('click','button',function(){cat=$(this).data('cat')||'';page=1;$('#filterList button').removeClass('active');$(this).addClass('active');render()});$('#pagination').on('click','button',function(){page=+$(this).data('page');render();$('html,body').animate({scrollTop:$('.products-area').offset().top-100},250)});render();
}
function detail(){if(!$('#detailTitle').length)return;let id=+(new URLSearchParams(location.search).get('id')||1),p=products.find(x=>x.id===id)||products[0],ic=categories.find(c=>c[1]===p.slug)?.[2]||'bi-box';$('#detailTitle').text(p.name);$('#detailCat').text(p.category);$('#detailDesc').text(p.desc);$('#detailImage').html(p.image?`<img src="${p.image}" alt="${p.name}">`:`<i class="bi ${ic}"></i>`);$('#metaBrand').text(p.brand);$('#metaPacking').text(p.packing);$('#metaOrigin').text(p.origin);$('#quoteProduct').val(p.name);$('#pageTitle').text(p.name);}
function brands(){if(!$('#brandsGrid').length)return;let names=['Ken Foods','Mondelle','Fletcher','GJ','Friboi','Minerva Foods','Nowaco','Pena Branca','Swift','Hayat'];$('#brandsGrid').html(names.map(n=>`<div class="brand-chip">${n}</div>`).join(''));}
function bind(){ $(document).on('click','.hamb',()=>$('.navlinks').toggleClass('show')); $(document).on('click','.navdrop>a',function(e){if(innerWidth<681){e.preventDefault();$('.navdrop').toggleClass('open')}}); $(document).on('keypress','#globalSearch',function(e){if(e.which===13)location.href='products.html?q='+encodeURIComponent(this.value)}); $(document).on('submit','.quote-form',function(e){e.preventDefault();$(this).find('.notice').text('Thank you. Your enquiry is ready to connect to your email/API.').show();});}
$(function(){shell();home();productPage();detail();brands();bind();});
})(jQuery);
